### ISSUE TITLE
wrong syntax in tests

### ISSUE THREAD

**Issue by alesak** [inspect-js/has-symbols#5]
/test/shams/core-js.js line 11

**return;** should not be there

/test/shams/get-own-property-symbols.js line 11

**return;** should not be there

those syntax errors causing IDEs to highlight your package as faulty

**Comment by ljharb** [comment]
It should, in fact, be there - these are node modules, in which top level return is allowed. If your IDE is marking it as a syntax error, your IDE is faulty.
