### ISSUE TITLE
Don't assume global

### ISSUE THREAD

**Issue by nvahalik** [inspect-js/has-symbols#6]
Angular CLI no longer supports global shims as of 6.x. Therefore this module will break projects which use it:
https://github.com/inspect-js/has-symbols/blob/aa57a17b19708906d1927f821ea8e73394d84ca4/index.js#L3

See also: https://github.com/ljharb/es-abstract/issues/59 and https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by ljharb** [comment]
Angular is the only thing that doesn’t support global - it’s a bug for it not to.

You can probably work around it by adding `window.global = window` to the front of your app code.

**Comment by fourgates** [comment]
I am also having this issues. I added the following code to polyfills.ts:

```
(window as any).global = window;
```

**Comment by ljharb** [comment]
Anything transforming node code for the browser should be transforming `global` to `window`. Please file a bug on any transformer that does not do this.
